#!/bin/bash
# This is a shell script for cloning mac addresses
# Show the message below
echo "Advertise with cloned MAC address"

# Get the current device mac address from the path of helpers / bdaddr / bdaddr
BDADDR=helpers/bdaddr/bdaddr

. ./config.env

# Get the hci number of the current device
HCIDEV="hci$BLENO_HCI_DEVICE_ID"

# Determine the number of input parameters, less than two returns an error
if [ $# -lt 2 ]; then
	echo "Usage: sudo $0 -a <advertisement_file> [ -s <services_file> ] "
	exit
fi

# Obtain the target ID from the input parameter two file
TARGETID=`echo $2 |cut -d "/" -f 2 | cut -d "_" -f 1`

# Obtain the target address from the file of the input parameter two
TARGETMAC=`echo $TARGETID | fold -w2 | paste -sd':' - | tr '[a-z]' '[A-Z]'`

HCIMAC=`hciconfig $HCIDEV |grep "Address" | cut -d" " -f 3`

# According to whether HCIMAC and TARGETMAC are equal, if not equal, copy TARGETMAC to HCIMAC
# The device can be recognized as a new mac address from the software
# case-insensitive - bash 4: 
while [ "${HCIMAC,,}" != "${TARGETMAC,,}" ]; do
	hciconfig $HCIDEV up
	$BDADDR -i $HCIDEV $TARGETMAC;
	echo "Re-plug the interface and hit enter";
	read 
	hciconfig $HCIDEV up
	HCIMAC=`hciconfig $HCIDEV |grep "Address" | cut -d" " -f 3`
	echo "Current MAC: $HCIMAC"
done
hciconfig $HCIDEV up

node advertise $1 $2 $3 $4
